# fly.toml app configuration file generated for affairsbot on 2026-03-09T20:55:58+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'affairsbot'
primary_region = 'sin'

[build]

[env]
  TIMEZONE = 'Asia/Singapore'
  SUBSCRIBERS_FILE = '/data/subscribers.json'

[mounts]
  source = 'affairsbot_data'
  destination = '/data'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
